workflows:
  detect_unity:
    name: Detect Installed Unity
    instance_type: mac_mini_m1

    scripts:
      - name: Show installed Unity versions
        script: |
          echo "===== UNITY VERSIONS INSTALLED ON CODMAGIC ====="
          ls /Applications/Unity/Hub/Editor/
      - name: STOP
        script: exit 1
