workflows:
  detect_unity_versions:
    name: Detect Unity Versions Installed on Codemagic
    instance_type: mac_mini_m1

    environment:
      xcode: latest

    scripts:
      - name: List installed Unity versions
        script: |
          echo "==============================="
          echo " UNITY VERSIONS ON THIS MACHINE"
          echo "==============================="
          ls /Applications/Unity/Hub/Editor/
      - name: STOP
        script: |
          echo "⛔ COPY THE UNITY VERSIONS ABOVE AND SEND TO ME"
          exit 1
