workflows:
  unity-ios-build:
    name: Unity iOS Build
    instance_type: mac_mini_m1

    environment:
      xcode: latest
      vars:
        UNITY_VERSION: "2022.3.20f1"
        UNITY_CHANGESET: "fb25bd87ecd7"   # chính xác change set của 2022.3.20f1
        BUILD_PATH: "build/ios"

    scripts:
      - name: Install Unity via Unity Hub
        script: |
          curl -O https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage
          chmod +x UnityHub.AppImage
          ./UnityHub.AppImage --headless install --version $UNITY_VERSION --changeset $UNITY_CHANGESET

      - name: Build Unity iOS Project
        script: |
          unity-editor \
            -batchmode \
            -quit \
            -projectPath . \
            -executeMethod BuildScript.BuildIOS \
            -logFile /dev/stdout

      - name: Build IPA using Xcode
        script: |
          cd $BUILD_PATH
          xcodebuild -scheme Unity-iPhone archive \
            -archivePath build/app.xcarchive
          xcodebuild -exportArchive \
            -archivePath build/app.xcarchive \
            -exportPath build/ipa

    artifacts:
      - build/ios/build/ipa/*.ipa
