workflows:
  unity-ios-build:
    name: Unity iOS Build
    instance_type: mac_mini_m1

    environment:
      vars:
        UNITY_PROJECT_PATH: "."
      xcode: latest

    scripts:

      - name: Detect Unity installation
        script: |
          echo "Searching Unity installations..."
          ls -1 /Applications/Unity/Hub/Editor/ || echo "Unity not found in Hub path"
          ls -1 /Applications/Unity || echo "Unity not found in default path"

      - name: Build Unity iOS project
        script: |
          UNITY_PATH=$(find /Applications/Unity/Hub/Editor -maxdepth 1 -type d | head -n 1)
          echo "Using Unity at: $UNITY_PATH"

          $UNITY_PATH/Unity.app/Contents/MacOS/Unity \
            -quit -batchmode -nographics \
            -projectPath "$UNITY_PROJECT_PATH" \
            -buildTarget iOS \
            -executeMethod BuildScript.BuildIOS \
            -logFile /dev/stdout

      - name: Build IPA from Xcode
        script: |
          cd build/ios
          xcodebuild -scheme Unity-iPhone \
                     -archivePath build.xcarchive archive \
                     -configuration Release
          xcodebuild -exportArchive \
                     -archivePath build.xcarchive \
                     -exportPath output \
                     -exportOptionsPlist ExportOptions.plist

    artifacts:
      - build/ios/output/*.ipa
      - build/**/Player.log
