workflows:
  unity-ios-build:
    name: Detect Unity versions and Build
    instance_type: mac_mini_m1

    environment:
      xcode: latest

    scripts:
      - name: List installed Unity versions
        script: |
          echo "== UNITY INSTALLED VERSIONS =="
          ls /Applications/Unity/Hub/Editor/

      - name: STOP here
        script: |
          echo "Copy the Unity version above and send to me. Then we continue."
          exit 1
