workflows:
  detect_unity_versions:
    name: Detect Unity Versions
    instance_type: mac_mini_m1

    environment:
      xcode: latest

    scripts:
      - name: List installed Unity versions
        script: |
          echo "== UNITY INSTALLED VERSIONS on Codemagic =="
          ls /Applications/Unity/Hub/Editor/
      - name: STOP
        script: |
          echo "👉 Copy the list and send to me."
          exit 1
