workflows:
  debug_unity:
    name: Debug Unity Path
    instance_type: mac_mini_m1

    scripts:
      - name: Show Unity versions
        script: |
          echo "=== Unity versions ==="
          ls -1 /Applications/Unity/Hub/Editor/
