workflows:
  detect_unity_versions:
    name: Detect Installed Unity Versions
    instance_type: mac_mini_m1

    scripts:
      - name: Show installed Unity versions
        script: |
          echo "===== UNITY VERSIONS INSTALLED ON CODMAGIC ====="
          ls -1 /Applications/Unity/Hub/Editor/
      - name: STOP
        script: exit 1
