workflows:
  unity-ios-build:
    name: Unity iOS Build
    instance_type: mac_mini_m1

    environment:
      unity: "2022.3.20f1"
      xcode: latest
      vars:
        BUILD_PATH: "build/ios"

    scripts:
      - name: Build Unity iOS Project
        script: |
          unity-editor \
            -batchmode \
            -quit \
            -projectPath . \
            -executeMethod BuildScript.BuildIOS \
            -logFile /dev/stdout

      - name: Build IPA using Xcode
        script: |
          cd $BUILD_PATH
          xcodebuild -scheme Unity-iPhone archive \
            -archivePath build/app.xcarchive
          xcodebuild -exportArchive \
            -archivePath build/app.xcarchive \
            -exportPath build/ipa

    artifacts:
      - build/ios/build/ipa/*.ipa
