workflows:
  unity-ios-build:
    name: Unity iOS Build
    instance_type: mac_mini_m1

    environment:
      vars:
        UNITY_VERSION: "2022.3.20f1"
        BUILD_PATH: "build/ios"
      xcode: latest

    scripts:
      - name: Select Unity version
        script: |
          set -e
          echo "Switching Unity version to $UNITY_VERSION"
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
            -batchmode \
            -quit

      - name: Build Unity iOS Project
        script: |
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
            -batchmode \
            -quit \
            -projectPath . \
            -executeMethod BuildScript.BuildIOS \
            -logFile /dev/stdout

      - name: Build IPA using Xcode
        script: |
          cd $BUILD_PATH
          xcodebuild -scheme Unity-iPhone archive \
            -archivePath build/app.xcarchive
          xcodebuild -exportArchive \
            -archivePath build/app.xcarchive \
            -exportPath build/ipa

    artifacts:
      - build/ios/build/ipa/*.ipa
