workflows:
  unity-ios-build:
    name: Unity iOS Build
    instance_type: mac_mini_m1

    environment:
      xcode: latest
      vars:
        BUILD_PATH: "build/ios"

    scripts:
      - name: List installed Unity versions
        script: |
          ls /Applications/Unity/Hub/Editor/

      - name: Build Unity iOS Project
        script: |
          /Applications/Unity/Hub/Editor/2021.3.29f1/Unity.app/Contents/MacOS/Unity \
            -batchmode \
            -quit \
            -projectPath . \
            -executeMethod BuildScript.BuildIOS \
            -logFile /dev/stdout

      - name: Build IPA using Xcode
        script: |
          cd $BUILD_PATH
          xcodebuild -scheme Unity-iPhone archive \
            -archivePath build/app.xcarchive
          xcodebuild -exportArchive \
            -archivePath build/app.xcarchive \
            -exportPath build/ipa

    artifacts:
      - build/ios/build/ipa/*.ipa
